USE [master]
GO

/****** Object:  Database [testdb]    Script Date: 8/24/2017 11:44:11 AM ******/
CREATE DATABASE [testdb]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'testdb', FILENAME = N'D:\IT-STEP\IT-Step-Repo\NodeJs\CW\Kris\Sql\MSSQL\db\testdb.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'testdb_log', FILENAME = N'D:\IT-STEP\IT-Step-Repo\NodeJs\CW\Kris\Sql\MSSQL\db\testdb_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [testdb] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [testdb].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [testdb] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [testdb] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [testdb] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [testdb] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [testdb] SET ARITHABORT OFF 
GO

ALTER DATABASE [testdb] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [testdb] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [testdb] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [testdb] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [testdb] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [testdb] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [testdb] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [testdb] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [testdb] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [testdb] SET  DISABLE_BROKER 
GO

ALTER DATABASE [testdb] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [testdb] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [testdb] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [testdb] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [testdb] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [testdb] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [testdb] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [testdb] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [testdb] SET  MULTI_USER 
GO

ALTER DATABASE [testdb] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [testdb] SET DB_CHAINING OFF 
GO

ALTER DATABASE [testdb] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [testdb] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [testdb] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [testdb] SET  READ_WRITE 
GO


